### ISSUE TITLE
createProject() returns 400 error

### ISSUE THREAD

**Issue by ryanhightower** [ajimix/asana-api-php-class#12]
I can't get createProject() to work. I am getting the correct workspace from getWorkspaces (I know this because I can create a task), but createProject always returns 400 error. Can you provide a code sample that works? 

Thanks so much for your help!

**Comment by nutank** [comment]
Hi, 
Even I can't get createProject working. Is there anything else that needs to be passed besides workspace,name and notes? 

```php
        $project_data = array('workspace' => $workspace_id, 'name' => $project_name,'notes' =>'Project notes');

        $created_project = $asana->createProject( $project_data );
```

I can create a task in the same workspace successfully but creation of project in the same workspace always returns 400 error. Are there any restrictions while creating project using API key?
