### ISSUE TITLE
Response time ridiculously slow on CURL execution

### ISSUE THREAD

**Issue by mmsheeks** [ajimix/asana-api-php-class#29]
Hey ajimix,

Not certain this is actually on your end, but the CURL calls are taking anywhere from 1 to 4 seconds to load their return data. This is fine for small calls, but on projects where I'm loading in a lot of tasks, load times take well over 40 seconds per page load.

Any idea how we could speed this up?

Best,

Martin

**Comment by mayankitt** [comment]
Hi ajimix,
What @mmsheeks mentions is right to a certain extent. My web application works only when I use the `set_time_limit();` function and that too on `localhost`. Once I uploaded the code to my web server for trials, the web page often returns `No Data Received` error:
![image](https://cloud.githubusercontent.com/assets/11437102/7558712/3adcc36a-f7c8-11e4-9125-00bd1df3a94a.png)

Any solutions?

**Comment by ajimix** [comment]
Hello @mayankitt this class is just a PHP wrapper on the Asana official API so the response time is something that has to do with Asana and not with this class itself.
If you have a lot of data to recover or the Asana servers are down/busy/whatever or your connection with Asana is not working properly this can happen, but again that is something out of this class scope.
I hope it helps :)

**Comment by mayankitt** [comment]
Hello @ajimix , I somewhat tried and figured out a solution. Though this is not very efficient as well, but it does help. I used the `opt_expand` index in the `$opts` array that can be passed as an argument in almost each one of your functions. It is again worthy to mention that your wrapper class really helped in a speedy development. Thank you. :-)
