### ISSUE TITLE
Undefined variable: info in C:\wamp\www\AGA\asana\asana.php on line 875

### ISSUE THREAD

**Issue by jangirashok** [ajimix/asana-api-php-class#37]
Hi,
Your API is amazing. Thanks for sharing. 
When I turned the debug mode to true in asana.php, the following error showed up:
Undefined variable: info in C:\wamp\www\AGA\asana\asana.php on line 875

$info["http_code"] variable was not available. I tried to go through all the possible places, but I couldn't find this one. 
Any hints?

Best,
Akki

**Comment by jangirashok** [comment]
Never mind!! Found it myself. 
 $info = curl_getinfo($curl); will do it. 
I think it is missing in your asana.php file. 
Thanks.

**Comment by ajimix** [comment]
Thanks. Just commited into master.
