### ISSUE TITLE
Association between Teams and Tasks.

### ISSUE THREAD

**Issue by mayankitt** [ajimix/asana-api-php-class#39]
Hi,

Your project has been a time saver for me and a lot of others. Thank you for that. Your wrapper class does everything that one might need.

However, I would want to know one thing. You have written down many functions like `getProjectTasks()`, `getTasksWithTag()`, etc. where one can retrieve tasks within a particular set. But there  seems to be no such function for getting tasks within Teams. By studying the data returned by Asana using your functions, there is no mention of a task belonging to a particular 'team'. Also, even when I export data as JSON through Asana's web application the teams find no mention. From what I understand, Asana itself does not provide an association between teams and tasks. Please correct me if I am wrong.

But if I am right at my conclusion, is there a workaround I could use? Teams are an important part of my data rendering and I need them to be mapped correctly in my reports that I am trying to generate from Asana. The report I want to generate would be hierarchical in nature:

Organization | Team | Project | Task
---------------- | ------- | -------- | -------
A | 1 | a | Task 1a
 |  |  | Task 2a
 | | b | Task 1b
 |  |  | Task 2b
 | 2 | c | Task 1c
 |  |  | Task 2c
B | 3 | d | Task 1d
 |  |  | Task 2d

Can I do something to achieve this hierarchy?

Regards,
Mayank Choudhary

**Comment by ajimix** [comment]
Hello, 
First of all, thank you for your writing, I created this class to help other people so I'm really happy to read your comments :)
Regarding what you need, I think is possible, give me one or two days and I'll update you, I'm sorry to not be able to fix it earlier but I'm pretty busy right now with other stuff.

I hope it's ok :)

**Comment by ajimix** [comment]
Hey @mayankitt 
Check new [2.10.0](https://github.com/ajimix/asana-api-php-class/releases/tag/2.10.0) version. It has support for getting the projects in a team so now you can use `getTeamsInOrganization`, `getProjectsInTeam` and `getProjectTasks` to build the report you want.

I hope it helps :)

**Comment by mayankitt** [comment]
Thanks a lot. It would definitely help I'm sure. :-)
