### ISSUE TITLE
createProject() returns 400 error

### ISSUE THREAD

**Issue by nutank** [ajimix/asana-api-php-class#40]
Hi, 
createProject method isn't working. Is there anything else that needs to be passed besides workspace,name and notes? 

```php
        $asana = new  Asana( array('apiKey' => $asana_key) );
        $project_data = array('workspace' => $workspace_id, 'name' => $project_name,'notes' =>'Project notes');

        $created_project = $asana->createProject( $project_data );
```

I can create a task in the same workspace successfully but creation of project in the same workspace always returns 400 error. Are there any restrictions while creating project using API key?

**Comment by ajimix** [comment]
Hello, just tried that sample code that I posted a while ago in #12 and it still works totally fine for me. Here is again a sample code:

```php
$asana = new Asana("MYAPIKEYBLABLABLA");

$asana->createProject(array(
    "workspace" => "1234567890", // Here I put the workspace where I want to create the project.
    "name" => "Foo Project!",
    "notes" => "This is a test project"
));
```

I tried this and it creates a new project inside the workspace I pass.

**Comment by nutank** [comment]
Hi @ajimix ,

Thanks for the reply. I think i know what the problem is. If the workspace is of type organization, then an additional parameter of 'team' needs to be passed.

```php
        $asana = new  Asana( array('apiKey' => $asana_key) );
        $project_data = array('workspace' => $workspace_id, 'name' => $project_name,'notes' =>'Project notes', 'team'=>$team_id);

        $created_project = $asana->createProject( $project_data );
```
Thanks again :+1:

**Comment by nutank** [comment]
@ajimix  Just to make a note, the default get request to workspaces does not return is_organization property.We need to specify ?opt_fields option. So the url would be of the form https://app.asana.com/api/1.0/workspaces?opt_fields=name,is_organization.

Right now getWorkspaces() method takes the default workspaces url and thus cannot be used to check whether a given workspace is of type organization or not. It would be great if this is added to the asana.php file.

**Comment by ajimix** [comment]
Thanks for pointing out. Just released `2.11.0` that accepts options to be passed to `getWorkspaces` method so you can specify this `opt_fields`

**Comment by nutank** [comment]
Thanks for updating!

**Comment by harryKamboj** [comment]
$asana = new Asana("----------------------------");
$result=$asana->createProject(array(
    "workspace" => $workspaceId, 
    "name" => "create new project"
));

i have lot of try to create the project .but not able to create the project using this code.
please help how i have to create the new project using asana API

**Comment by ajimix** [comment]
Hello @harryKamboj 
Just tried now with this code and totally work for me:
```php
$asana = new Asana(array('apiKey' => 'XXXXXXXXXX'));

$asana->createProject(array(
	'workspace' => 'XXXXXXXX',
	'name' => 'Some random name 1234'
));
```

Please make sure you are using proper workspace ID and proper API key

**Comment by harryKamboj** [comment]
Thanks for reply sir.
yes it work  for simply asana to add the project .but we need for organization particular team  to add the project . i am got now how to get the team id and than add the project for particular organization.now insert the project is working fine
