### ISSUE TITLE
Line Breaks in Notes

### ISSUE THREAD

**Issue by Stephen304** [ajimix/asana-api-php-class#43]
Maybe I'm doing something wrong, but I can't seem to get line breaks to show up in the notes of tasks.

I've tried \n, \n\r, &lt;br&gt;, but they all just render as is. Any ideas? My code looks like:

```
  $result = $asana->createTask(array(
      'workspace' => '498346170860',
      'projects' => array('35253997924569'),
      'name' => 'Contact: '.$_GET['name'],
      'notes' => 'Contact Information:\n\r'.$_GET['name'].'\n\rPhone: '.$_GET['phone'].'\n\rEmail: '.$_GET['email'],
      'assignee' => 'stephen304@gmail.com'
  ));
```

**Comment by ajimix** [comment]
Hello, as you can see in [this stackoverflow response](http://stackoverflow.com/questions/25910618/formatting-issue-while-creating-new-tasks-using-api) you need to use a real new line character as the wrapper is sending the request via normal form data and not via JSON.

**Comment by Stephen304** [comment]
Ah, I assumed it was sending via json. Thanks!

**Comment by Stephen304** [comment]
Holy mess it was actually the quotes - double quotes necessary for escape characters to work.
