### ISSUE TITLE
Not working on localhost

### ISSUE THREAD

**Issue by DsEsteban** [ajimix/asana-api-php-class#48]
Hey! im trying to use those examples on my localhost, but it's not working. Im getting a 500 status always...i know it's not your code but my server..but, do you have any clue about what can i do? i'd reallly appreciate it (':

**Comment by ajimix** [comment]
Hello, could you please provide more information? I just tried a couple of examples to see if they work and they work totally fine on my machine. Perhaps if you can provide a little bit more information I can help you :)
