### ISSUE TITLE
issues at creating new task in api

### ISSUE THREAD

**Issue by sirajshaikh** [ajimix/asana-api-php-class#50]
Trying to create a new task just like new-task-to-project.php
 but task id is genrated  EX (1.015460109095E+14) like this but new task is not adding and showing Error (while assigning project to task :404 error,).

$projectId & $taskId both are proper but no result..

```
`$asana->createTask(array(
    "workspace" => "99915435644125", // Workspace ID
    "name"      => "Getting all info"// Name of task
));


if ($asana->hasError()) {
    echo 'Error while project data: ' . $asana->responseCode;
	return;
  } else{
		$taskId = $asana->getData()->id; 
		echo $taskId;
		echo "<br>".$projectId."<br>";
		
		$asana->addProjectToTask($taskId,$projectId);
		if ($asana->hasError()) {
			echo 'Error while assigning project to task: ' . $asana->responseCode;
		} else {
			echo 'Success to add the task to a project.';
		}
}
`
```

**Comment by ajimix** [comment]
Hey @sirajshaikh I just did this test with the latest version of the code and using my credentials and projects and worked fine. Are you sure you are using the right project ID?

**Comment by sirajshaikh** [comment]
Hey @ajimix  Thanks for your replay .Yes code is perfect when i try to generate new ID with this code
`$taskId = $asana->getData()->id; `
 then id genrated As 1.015460109095E+14)...

**Comment by sirajshaikh** [comment]
Hey @ajimix ..

problem is solved it occur  just because of browser integer number limitation. we need to user 1 more line like this..
`$taskId = $asana->getData()->id;`

`echo number_format($taskId,0,null,'');`

then we are going proper ID (EX :- 10154601090956) 

i just create simple application with only important function and upload in my account using your API may be its help full for some one Like me..

Thanks For Doing a great job @ajimix ......

**Comment by ajimix** [comment]
Hey @sirajshaikh I'm glad you make it work. Then it's not a problem about the library but about the task id display of the number. I'm closing this issue. Thanks
