### ISSUE TITLE
No more api key availability

### ISSUE THREAD

**Issue by thorakmedichi** [ajimix/asana-api-php-class#55]
So Asana has now removed the API key ability to create tasks.

However they do have a personal token that you can have each user create and use.

Any plans to update this code so it will work again without switching to OAuth??

**Comment by ajimix** [comment]
Just added support for it in version [4.0.0](https://github.com/ajimix/asana-api-php-class/commit/a3f968f9be5fad02cb4aa5294f55a9665cb74728) I hope it helps 👍
