### ISSUE TITLE
400 error

### ISSUE THREAD

**Issue by Jpfleger** [ajimix/asana-api-php-class#56]
Hi, 
I seem to be getting a 400 error when trying to use any of the create methods:

`
$workspaceId = '<id>';
$teamId = '<id>';
$asana->createProject([
   'name'=>'project Name',
   'workspace'=>$workspaceId,
   'team'=>$teamId,
   'notes'=>'some notes'
]);
`

**Comment by thetwosents** [comment]
I have createProject working okay but getting 500 errors on createTask

```$project = $asana->createProject(array(
	'team' => $teamId,
	'name' => $projectName,
	'notes' => $projectNotes
));```

**Comment by Jpfleger** [comment]
Removing the workspaceId corrected my issue.
