### ISSUE TITLE
Packagist cannot reach 4.2

### ISSUE THREAD

**Issue by rvanlaak** [ajimix/asana-api-php-class#58]
We can not install `~4.2`, it seems Packagist is not in sync with the repo: https://packagist.org/packages/ajimix/asana-api-php-class

Did you setup the service hook? https://packagist.org/about#how-to-update-packages

**Comment by ajimix** [comment]
Thanks for reporting this. The webhook was setup, but for some reason, it didn't work for the last commit. Anyway, please check now as it should work now :) 👍

**Comment by rvanlaak** [comment]
Yes that's it, thanks for your fast reply 👍
