### ISSUE TITLE
Custom Fields

### ISSUE THREAD

**Issue by bobcomp11** [ajimix/asana-api-php-class#60]
Anyone know how to add a custom field when creating a task?

**Comment by ajimix** [comment]
Hello @bobcomp11 you should be able to do it like that:
```php
$asana->createTask([
  'workspace' => '176825', // Workspace ID
  'name' => 'Hello World!', // Name of task
  'assignee' => 'bigboss@bigcompany.com', // Assign task to...
  'custom_fields' => [{
    id: 1646, // Custom field ID
    name: 'Something', // Name of the custom field
    type: 'string', // Type
    string_value: 'Test' // Value
  ]
]);
```

You can read more about the data in the [Asana documentation](https://asana.com/developers/api-reference/tasks)

**Comment by ajimix** [comment]
I've also just released version 5.0.0 which includes support for managing custom tags in general. But the answer which I posted before works also with previous library versions.
I'm closing this issue, please reopen if you have more problems.

**Comment by bobcomp11** [comment]
Thanks Adria,

What am I doing wrong this is the entire array and if I comment out the custom fields stuff it creates the task just fine. 

// First we create the task
$result = $asana->createTask(array(
    'workspace' => $workspaceId, // Workspace ID
    'name'      => 'Test Task', // Name of task
	'assignee' => 'mlabib@kent.edu',
	'custom_fields' => [{id: 272990899523522, name: 'First Name', type: 'string', string_value: { id: 272990899523522, name: 'Mark' }}]
));

Bob Baumann
bbaumann1129@gmail.com

**Comment by ajimix** [comment]
Hey @bobcomp11 sorry my confusion, it looks like it's not string but text. Please try this code:
```php
$result = $asana->createTask(array(
    'workspace' => $workspaceId, // Workspace ID
    'name'      => 'Test Task', // Name of task
    'assignee' => 'mlabib@kent.edu',
    'custom_fields' => [{
        id: 272990899523522,
        name: 'First Name',
        type: 'text',
        text_value: 'Mark'
    }]
));
```

This is at least what the documentation says [here](https://asana.com/developers/api-reference/tasks#custom-field-values)

I hope it helps

**Comment by bobcomp11** [comment]
He is exactly what I have 

// First we create the task
$result = $asana->createTask(array(
    'workspace' => $workspaceId, // Workspace ID
    'name'      => 'Test Task', // Name of task
	'assignee' => 'mlabib@kent.edu',
	'custom_fields' => [{id: 272990899523522, name: 'First Name', type: 'text', text_value: 'Mark'}]
));

I believe it is a syntax error somewhere as the page is just blank and it doesn’t even produce an error message.

Bob Baumann
bbaumann1129@gmail.com

**Comment by ajimix** [comment]
@bobcomp11 my mistake again, sorry the array notation is wrong...
```php
$result = $asana->createTask(array(
    'workspace' => $workspaceId, // Workspace ID
    'name'      => 'Test Task', // Name of task
    'assignee' => 'mlabib@kent.edu',
    'custom_fields' => [{
        id => 272990899523522,
        name => 'First Name',
        type => 'text',
        text_value => 'Mark'
    }]
));
```

Sorry but I was doing javascript when answering you the first time this morning and in javascript is the other way :D

Let's see if it works now

**Comment by bobcomp11** [comment]
Still produces a blank page. If I comment out the custom fields it works fine.

Bob Baumann
bbaumann1129@gmail.com

**Comment by ajimix** [comment]
Please kill me :D

```php
$result = $asana->createTask(array(
    'workspace' => $workspaceId, // Workspace ID
    'name'      => 'Test Task', // Name of task
    'assignee' => 'mlabib@kent.edu',
    'custom_fields' => [{
        'id' => 272990899523522,
        'name' => 'First Name',
        'type' => 'text',
        'text_value' => 'Mark'
    }]
));
```

Now it's 100% the proper syntax lol

**Comment by bobcomp11** [comment]
Still throwing a blank page here is the entire file

<?php
error_reporting( E_ALL );
require_once('asana.php');

// See class comments and Asana API for full info
$asana = new Asana(array('personalAccessToken' => '0/d0d725b980f15e0dbea69d96e0480839')); // Create a personal access token in Asana or use OAuth

$workspaceId = '215062504971739'; // The workspace where we want to create our task
$projectId   = '215852122503309'; // The project where we want to save our task

$result = $asana->createTask(array(
    'workspace' => $workspaceId, // Workspace ID
    'name'      => 'Test Task', // Name of task
    'assignee' => 'mlabib@kent.edu',
    'custom_fields' => [{
        'id' => 272990899523522,
        'name' => 'First Name',
        'type' => 'text',
        'text_value' => 'Mark'
    }]
));

echo $result;

// As Asana API documentation says, when a task is created, 201 response code is sent back so...
if ($asana->hasError()) {
    echo 'Error while trying to connect to Asana, response code: ' . $asana->responseCode;
    return;
}

$taskId = $asana->getData()->id; // Here we have the id of the task that have been created

// Now we do another request to add the task to a project
$asana->addProjectToTask($taskId, $projectId);

if ($asana->hasError()) {
    echo 'Error while assigning project to task: ' . $asana->responseCode;
} else {
    echo 'Success to add the task to a project.';
}

Bob Baumann
bbaumann1129@gmail.com

**Comment by ajimix** [comment]
There were two extra braces...

```php
$result = $asana->createTask(array(
    'workspace' => $workspaceId, // Workspace ID
    'name'      => 'Test Task', // Name of task
    'assignee' => 'mlabib@kent.edu',
    'custom_fields' => [
        'id' => 272990899523522,
        'name' => 'First Name',
        'type' => 'text',
        'text_value' => 'Mark'
    ]
));
```

I suggest you to install a php linter to your editor that way you will be able to quickly detect syntax errors :)

Sorry but I'm programming in javascript and answering your php emails and this context switching makes me not see the errors.

**Comment by bobcomp11** [comment]
Thank you that now works but gives us a 400 error with asana? Do you have any experience with that?

Bob Baumann
bbaumann1129@gmail.com

**Comment by ajimix** [comment]
[Here](https://asana.com/developers/documentation/getting-started/errors) you can see the error codes.

Are you sure the custom field id you are using exists?

Also, try to use type `string` and `string_value` instead of `text` and `text_value` like I said in the beginning. There seems to be a confusion in the documentation and I don't know which one is the right one and I don't have Asana premium to try it out.

**Comment by bobcomp11** [comment]
This is what I have now and we are still getting the bad request error.

400	Invalid request	This usually occurs because of a missing or malformed parameter. Check the documentation and the syntax of your request and try again.

Maybe it is an issue on asana's end.


$result = $asana->createTask(array(
    'workspace' => $workspaceId, // Workspace ID
    'name'      => 'Test Task', // Name of task
    'assignee' => 'mlabib@kent.edu',
    'custom_fields' => [
        'id' => 272990899523522,
        'name' => 'First Name',
        'text_value' => 'Mark',
	    'type' => 'text'
    ],
	'due_on' => '2012-03-26'
));


Bob Baumann
bbaumann1129@gmail.com

**Comment by ajimix** [comment]
Did you try with string and string value?

```php
$result = $asana->createTask(array(
    'workspace' => $workspaceId, // Workspace ID
    'name'      => 'Test Task', // Name of task
    'assignee' => 'mlabib@kent.edu',
    'custom_fields' => [
        'id' => 272990899523522,
        'name' => 'First Name',
        'type' => 'string',
        'string_value' => 'Mark'
    ]
));
```

**Comment by bobcomp11** [comment]
Yes both string and text throw that same error.

Bob Baumann
bbaumann1129@gmail.com

**Comment by ajimix** [comment]
Ok, can you try `$asana->getCustomField(272990899523522);` and see if you can print a result?

**Comment by bobcomp11** [comment]
Putting that in the current file it displays a blank page again.

Bob Baumann
bbaumann1129@gmail.com

**Comment by ajimix** [comment]
Are you paying the Asana premium?

**Comment by bobcomp11** [comment]
Yes I have a 10 user account.

Bob Baumann
bbaumann1129@gmail.com

**Comment by bobcomp11** [comment]
Adria after talking with their API team you cant put custom fields into tasks yet. They are only read only.

Bob Baumann
bbaumann1129@gmail.com

**Comment by ajimix** [comment]
Hey Bob, thanks for updating this. And good to know! It's sad that the documentation of their API doesn't say that and that made us waste some hours trying to figure out the problem :(
Thanks for taking the time to post an update :) 👍
