### ISSUE TITLE
getProjectTasks() returns empty if the list > 1000

### ISSUE THREAD

**Issue by tmiecz** [ajimix/asana-api-php-class#63]
Hi Adria,

I've been using your code for few weeks now and everything seemed to work well until my list got a bit out of hand. It took me a little while to troubleshoot it, but I ended up finding that if the list contains more than 1000 items, it just won't return anything.

That includes completed tasks too, so even if I have 5 items in my list but completed 996 tasks before, it would return null.

Cheers,
T.

**Comment by zeeshanyshaikh** [comment]
Asana returns 100 task per request. If you have more than 100 tasks you need loop through it. For every request if its more than 100 then Asana gives a token to query for next page/100.

**Comment by tmiecz** [comment]
I don't think we're talking about the same thing.

I'm saying that the following call in this project: **getProjectTasks()** returns an empty array when the project itself has more than 1,000 tasks. When you have 999 tasks in a single project, it will return 999 tasks. When you have 1,000 tasks it returns 0 tasks.
