### ISSUE TITLE
Creating task doesnt work.

### ISSUE THREAD

**Issue by jack-fdrv** [ajimix/asana-api-php-class#70]
Asana responded with HTTP error: 400

**Comment by ajimix** [comment]
Hello @jack-fdrv I just made a test with the `examples/task-creation.php` file and it's working for me. So must be something you are doing wrong, please test with the example file and adapt your code to match the example.

**Comment by jack-fdrv** [comment]
Agree, my bad.
Error messages do not work.
So I try to copy request in postman and only after that I realise the problem with tag id on task creation.

Btw, thank you man for this library. 
Easy and fun! =)

**Comment by jack-fdrv** [comment]
Dear ajimix, can I ask you one more question.
How I can use function "addAttachmentToTask"?
I try to add images to my task:

`$data = [$image, wp_check_filetype($image)['type'], basename($image)];
			$asana->addAttachmentToTask($taskId, $data);`

Print of $data:
`Array
(
   [0] => https://doain.com.au/wp-content/uploads/2019/08/tw-5.png
   [1] => image/png
   [2] => tw-5.png
)`

But it doesnt work.
I also tried file_get_contents. 

You said "$data (src of file, mimetype, finalFilename) See, Uploading an attachment to a task function comments for proper parameter info." but what did you mean with "src of file"?

**Comment by ajimix** [comment]
@jack-fdrv the param $data should be like the following example:

```php
$data = [
  'file' => 'cats.jpg',
  'mimeType' => 'image/jpeg',
  'finalFilename' => 'cats_final.jpg'
];
```

The file must be a local file in your server so if it's uploaded online, you will have to download the file first to the server before using it

**Comment by jack-fdrv** [comment]
But file can be like a path to the local file?
Or it should be in the same directory?

**Comment by ajimix** [comment]
It can be a path as soon as it's reachable by the asana.php class

**Comment by jack-fdrv** [comment]
Thank you very much =) 
You are like a Iron man, philanthropist.

**Comment by jack-fdrv** [comment]
Seems it doenst work.

Try to add
`$data = [
	'file' => 'in.png',
	 'mimeType' =>  wp_check_filetype('in.png')['type'],
	'finalFilename' => 'in.png'
];
			
$asana->addAttachmentToTask($taskId, $data);`

Data print:

`Array
(
   [file] => in.png
   [mimeType] => image/png
   [finalFilename] => in.png
)`
I've put image in the same apth, where my php script calling it.
Also I put the same image in folder with ur asana class.

Here the debug info:
https://src.fdrv.guru/190815211930.jpg

**Comment by jack-fdrv** [comment]
Works =)

**Comment by jack-fdrv** [comment]
```
$data = [
  'file' => 'cats.jpg',
  'mimeType' => 'image/jpeg',
  'finalFilename' => 'cats_final.jpg'
];
```
We should use full path to the file.
